version: '3'
services:
  app:
    build: .
    expose:
      - "5000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
